---
title: "我的 Vim 实践之路"
date: 2018-06-02T11:44:30+08:00
draft: false
tags: ["Vim"]
---

= 我的 Vim 实践之路
:experimental:

== 接触

记得一开始是从《鸟哥的 Linux 私房菜》了解到 Vim 的。当初刚开始接触 Linux，正在
用那本书学习 Linux。虽然学习曲线陡，但现在习惯了 Vim 的模式之后，已经越来越离不
开了，成了电脑上的必装软件。各个软件装的第一个插件就是用于模拟 Vim 操作的插件。

== 入门

第一次接触 Vim 的时候，还是挺惊讶的，没想到 Linux 下面有这么好玩、高级的工具（
虽然 Vim 并不是只存在与 Linux 下面，但我确实是接触了 Linux 才知道 Vim 的）。在
网上了解了下，发现它的学习曲线还是挺陡的。但经不住类似于“掌握了 Vim/Emacs，可以
一招走天下，不用再去学习其他编辑器了“、”在服务器上修改一个文件，只有 Vim 可选“
的诱惑和”恐吓“，就入坑了。

我是利用 Vim 自带的教材和用户手册来学习的，免去了寻找和选择教程的烦恼，还可以训
练自己的英文文档阅读能力（从那以后，学习命令、软件，都习惯了先从自带的手册、帮
助文档开始）。先过了几遍 vimtutor 教程，了解了 Vim 的几个模式和基本操作命令之后
，就开始看用户手册了。一边看手册、一边实验，顺便做殿笔记，几个星期下来，除了几
章暂时不感兴趣外，其他的都过了一遍，这个过程中，Vim 也用得越来越顺手了。接下来
就是多练习，平时记点东西用 Vim，写 C 用 Vim，写 Python 用 Vim，甚至写 Java 也用
过一段时间的 Vim。

刚入门的时候，当然就少不了去折腾 Vim 配置和插件，比如：airline、Vundle、
YouCompleteMe、gdbmgr 等等，看各种将 Vim 配置成 IDE 的教程，插件自带文档。那个
时候Vim 配置文件总是改来改去，一下用这个插件、一下又用另一个替换掉。

== 日常

后来慢慢意识到有些场合使用 Vim 并不是最高效的，转向使用其他软件加 Vim 插件的方
式。下面就聊聊日常使用场景：

=== 开发

写代码的时候，特别是 Java 代码，使用 IDE 还是能方便很多的。IDE 可以做到自动补全
、自动导包、错误提示……，不过很多时候需要借助鼠标进行操作，即使可以使用快捷键，
但各个 IDE 的快捷键又不尽相同；而用 Vim 编写代码，双手可以做到在不离开主键盘的
情况下快速地完成大部分操作。为了做到两者兼得，这个时候就可以借助 IDE 模拟 Vim
操作的插件了。比如：Eclipse 的Vrapper、IDEA 的 IdeaVim，这样我们可以使用 Vim 的
键盘映射方式进行编码，也就不用担心各个 IDE 不同的快捷键问题了。这也是很多人推荐
学习 Vim/Emacs 的原因：只需要学一遍，到处都可以使用。类似于 Java 的“write once
，run anywhere”，哈哈～

=== 浏览网页

上网也是一种频繁使用鼠标的场景。上网的时候，很多人还会养成一个把手一直放鼠标上
的习惯。这个时候，我们也可以借助 Vim 插件大大减少使用鼠标的次数，从而避免这种坏
习惯。比如 Chrome 有 Vimium，Firefox 有 Vimperator（不支持Firefox 57+，不过
Vimium 有一个针对 Firefox 的移植版本）。当初从 Firefox 转向 Chrome 主要就是因为
Vimium 。Vimium 在打开链接时，生成的按键更加合理，基本都在放置手指的附近；而
Vimperator 生成的按键都是数字，每次都需要移动手指去按。上面这些插件学起来也不难
，只需要了解几个常见的命令就可以满足大部分的需求，比如 Vimium 的
kbd:[f]/kbd:[F]（打开链接）、kbd:[x]（关闭当前 tab 页）、kbd:[H]（后退）、
kbd:[L]（前进），非常方便。

=== Vim 自身

Vim 自身并没有因此被抛弃，它本身是一个文本编辑器，所以文本编辑工作我还是交给它
进行处理。比如日常中会遇到：将所有的字符全部转为大写或小写、查找替换、排序、去
重、批量处理……，这个时候 Vim 能很方便地完成。

== 最后

Vim 学习曲线虽陡，但投入适当的时间学习一遍，就可以受用整个职业生涯，能够驾驭各
个场景（比如上面说的编码、上网、文本处理），这种投入还是非常值得的。
